# Generated by Django 5.0.6 on 2024-06-05 09:45

import authApp.models
import creditcards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(default=authApp.models.id_generator, primary_key=True, serialize=False)),
                ('cc_number', creditcards.models.CardNumberField(max_length=25, verbose_name='Card Number')),
                ('cc_expiry', creditcards.models.CardExpiryField(verbose_name='Expiration Date')),
                ('cc_code', creditcards.models.SecurityCodeField(max_length=4, verbose_name='CVV/CVC')),
            ],
        ),
    ]
